version: '3.8'
services:
   web:
       build: .
       command: python manage.py runserver localhost:8000
       ports:
           - 8000:8000
   app:    
       command: python manage.py createsuperuser
       volumes:
              - .:/code
       depends_on:
              - db
db:
         image: postgres
         environment:
              POSTGRES_PASSWORD: 12345
              POSTGRES_USER: admin
              POSTGRES_DB: postgres
         volumes:
              - db_data:/var/lib/postgresql/data/
