# Generated by Django 4.0.5 on 2022-07-14 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('model_p', models.CharField(max_length=100)),
                ('count_p', models.IntegerField()),
                ('params', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('margin', models.IntegerField()),
                ('price', models.IntegerField(blank=True, null=True)),
                ('parts', models.ManyToManyField(related_name='carss', to='carsdb.parts')),
            ],
        ),
        migrations.CreateModel(
            name='car_part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carsdb.cars')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carsdb.parts')),
            ],
        ),
    ]
